const express = require('express')
const cors = require('cors')
const dbConnect = require('./config/db.config')
require('dotenv').config()
const app = express()
const PORT = process.env.PORT || 5101
const userRouter = require('./routes/user.routes')
const quizRouter = require('./routes/quiz.routes')
const resultRouter = require('./routes/result.routes')
const authenticateUser = require('./middlewares/auth.middleware')
app.use(cors())
app.use(express.json())
app.use(express.urlencoded({extended: true}))
app.get('/', (req, res) => {
    res.send('<h1>Quizzicular api</h1>')
})
app.use('/user', userRouter)
app.use('/quiz', authenticateUser, quizRouter)
app.use('/result', authenticateUser, resultRouter)
dbConnect()
app.listen(PORT)